apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapfs-device
  namespace: mapfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mapfs-device
  template:
    metadata:
      labels:
        app: mapfs-device
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8012"
        # Opcional: prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: mapfs-device
          image: mapfs-device:latest
          imagePullPolicy: Never
          command: ["python", "-m", "device.mapfs_device"]
          ports:
            - containerPort: 8012
          volumeMounts:
            - name: logs
              mountPath: /logs
      volumes:
      - name: logs
        emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: mapfs-device
  namespace: mapfs
spec:
  selector:
    app: mapfs-device
  ports:
  - name: prometheus
    port: 8012
    targetPort: 8012
  type: ClusterIP

