apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: mapfs
data:
  promtail-config-template.yml: |
    server:
      http_listen_port: 9080
    positions:
      filename: /var/lib/promtail/positions.yaml 
    clients:
      - url: http://loki.mapfs.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
      - job_name: system-logs
        static_configs:
          - targets: ["localhost"]
            labels:
              job: "varlogs"
              host: "k8s-node"
              __path__: /var/log/*.log

      - job_name: docker-logs
        pipeline_stages:
          - docker: {}
        static_configs:
          - targets: ["localhost"]
            labels:
              job: "docker"
              host: "${HOSTNAME}"
              cluster: "local-cluster-promtail-kvsalazar"
              __path__: /var/lib/docker/containers/*/*-json.log

      - job_name: containerd-logs
        pipeline_stages:
          - cri: {}
        static_configs:
          - targets: ["localhost"]
            labels:
              job: "k8s-containers"
              host: "${HOSTNAME}"
              cluster: "local-cluster-promtail-kvsalazar"
              __path__: /var/log/pods/*/*/*.log