apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mapfs
data:
  grafana-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.mapfs.svc.cluster.local:3100
        access: proxy
        isDefault: false

      - name: Prometheus
        type: prometheus
        url: http://prometheus.mapfs.svc.cluster.local:9090
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          scrapeInterval: "5s"