apiVersion: v1
kind: PersistentVolume
metadata:
  name: sniffer-shared-pv
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi  
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/sniffing-data"
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sniffer-shared-pvc
  namespace: mapfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi  # Debe coincidir con la capacidad o ser menor

