apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: mapfs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - namespaces
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-binding
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: mapfs
roleRef:
  kind: ClusterRole
  name: fluent-bit-role
  apiGroup: rbac.authorization.k8s.io
